### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by joshp23** [jessebs/namesilo_ddns#1]
N/M

**Comment by jessebs** [comment]
I'm assuming since you closed it, you figured out how to use the script. I'm going to reopen this ticket and add some examples to the readme.

Hopefully you are finding it useful.

**Comment by jessebs** [comment]
Duplicated by #2 since I cannot reopen this issue.

**Comment by joshp23** [comment]
I should have edited my first comment to be, "a Google search will provide this info... I need to stop being lazy," buy I appreciate the addition of simple instruction... I'm sure someone else will find it helpful when in the same situation as me.
